packages:
  - playground
  - docs
  - demo

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - vue-demi

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver
